mvc/Controllers/SkelbimasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace mvc.Models
{
    public class SkelbimasController : Controller
    {
        private readonly darbasContext _context;

        public SkelbimasController(darbasContext context)
        {
            _context = context;
        }

        // GET: Skelbimas
        public async Task<IActionResult> Index(string sortOrder, string Raktazodis, int? puslapis, string currentFilter, string kategorija)
        {
            var darbasContext = _context.Skelbimas.Include(s => s.FkKategorija).Include(s => s.FkVartotojas).Include(s => s.MokejimoBudasNavigation);
            if (Raktazodis != null)
            {
                puslapis = 1;
            }
            else
            {
                Raktazodis = currentFilter;
            }
            ViewData["CurrentFilter"] = Raktazodis;
            ViewData["Kategorija"] = kategorija;
            var skelbimai = from s in _context.Skelbimas select s;

            if (!String.IsNullOrEmpty(Raktazodis))
            {
                skelbimai = skelbimai.Where(s => s.Pavadinimas.Contains(Raktazodis));
            }
            if (!String.IsNullOrEmpty(kategorija))
            {
                skelbimai = skelbimai.Where(s => s.FkKategorija.Pavadinimas.Contains(kategorija));
            }

            int pageSize = 5;
            return View(await PaginatedList<Skelbima>.CreateAsync(skelbimai.AsNoTracking().Include(d => d.FkVartotojas), puslapis ?? 1, pageSize));
        }

        // GET: Skelbimas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["ID"] = id;
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var skelbima = await _context.Skelbimas
                .Include(s => s.FkKategorija)
                .Include(s => s.FkVartotojas)
                .Include(s => s.MokejimoBudasNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (skelbima == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var komentarai = _context.Komentaras.Where(a => a.FkSkelbimasid == id).ToList();
            foreach (Komentara c in komentarai)
            {
                var user = await _context.Vartotojas.FirstOrDefaultAsync(z => z.Id == c.FkVartotojasid);
                c.FkVartotojas.Vardas = user.Vardas;
                skelbima.Komentaras.Add(c);
            }

            return View(skelbima);
        }

        // GET: Skelbimas/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas");
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas");
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name");
            return View();
        }

        // POST: Skelbimas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Pavadinimas,Aprasymas,Adresas,Uzmokestis,Data,MokejimoBudas,Id,FkVartotojasid,FkKategorijaid")] Skelbima skelbima)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
                skelbima.Data = DateTime.Now;
                skelbima.FkVartotojasid = user.Id;
                _context.Add(skelbima);
                await _context.SaveChangesAsync();
                TempData["pavyko"] = "Skelbimas buvo sėkmingai sukurtas!";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas", skelbima.FkKategorijaid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas", skelbima.FkVartotojasid);
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name", skelbima.MokejimoBudas);
            return View(skelbima);
        }

        // GET: Skelbimas/Prisiminti
        [Authorize]
        public IActionResult Prisiminti(int id)
        {
            ViewData["ID"] = id;
            var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
            var isiminti = _context.Isiminta.Count(x => x.FkSkelbimasid == id);
            var isi = _context.Isiminta.Where(y => y.FkSkelbimasid == id).ToList();
            foreach (var i in isi)
            {
                if (i.FkVartotojasid == user.Id)
                {
                    TempData["Error"] = "Klaida! Jūs šį skelbimą jau esate įsiminę!";
                    return Redirect("~/Home");
                }
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas");
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas");
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name");
            return View();
        }

        // POST: Skelbimas/Prisiminti
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]

        public async Task<IActionResult> Prisiminti([Bind("FkSkelbimasid,FkVartotojasid")] Isimintum isimintum, int id)
        {
            var isiminti = _context.Isiminta.Count(x => x.FkSkelbimasid == id);
            if (ModelState.IsValid)
            {
                var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
                isimintum.FkSkelbimasid = id;
                isimintum.FkVartotojasid = user.Id;
                _context.Add(isimintum);
                await _context.SaveChangesAsync();
                TempData["pavyko"] = "Skelbimas buvo sėkmingai prisimintas!";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkSkelbimasid"] = new SelectList(_context.Skelbimas, "Id", "Aprasymas", isimintum.FkSkelbimasid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "EPastas", isimintum.FkVartotojasid);
            return View(isimintum);
        }

        // GET: Skelbimas/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var skelbima = await _context.Skelbimas
                .Include(s => s.FkKategorija)
                .Include(s => s.FkVartotojas)
                .Include(s => s.MokejimoBudasNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (skelbima == null)
            {
                return Redirect("~/Home/Nerasta");
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas", skelbima.FkKategorijaid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas", skelbima.FkVartotojasid);
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name", skelbima.MokejimoBudas);
            return View(skelbima);
        }

        // POST: Skelbimas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Pavadinimas,Aprasymas,Adresas,Uzmokestis,Data,MokejimoBudas,Id,FkVartotojasid,FkKategorijaid")] Skelbima skelbima)
        {
            if (id != skelbima.Id)
            {
                return Redirect("~/Home/Nerasta");
            }

            if (ModelState.IsValid)
            {
                var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
                skelbima.FkVartotojasid = user.Id;
                skelbima.Data = DateTime.Now;
                try
                {
                    _context.Update(skelbima);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkelbimaExists(skelbima.Id))
                    {
                        return Redirect("~/Home/Nerasta");
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["pavyko"] = "Skelbimas buvo sėkmingai atnaujintas!";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas", skelbima.FkKategorijaid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas", skelbima.FkVartotojasid);
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name", skelbima.MokejimoBudas);
            return View(skelbima);
        }

        // GET: Skelbimas/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

mvc/Controllers/VartotojasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc.Models;

namespace mvc.Controllers
{
    public class VartotojasController : Controller
    {
        private readonly darbasContext _context;

        public VartotojasController(darbasContext context)
        {
            _context = context;
        }

        // GET: Vartotojas
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vartotojas.ToListAsync());
        }

        // GET: Vartotojas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var vartotoja = await _context.Vartotojas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vartotoja == null)
            {
                return Redirect("~/Home/Nerasta");
            }
            return View(vartotoja);
        }

        // GET: Vartotojas/Isiminti/5
        [Authorize]
        public IActionResult Isiminti()
        {
            return View();
        }

        // GET: Vartotojas/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vartotojas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Vardas,Slaptazodis,Telefonas,EPastas,Miestas,Id")] Vartotoja vartotoja)
        {
            if (ModelState.IsValid)
            {
                vartotoja.Slaptazodis = BCrypt.Net.BCrypt.HashPassword(vartotoja.Slaptazodis);
                _context.Add(vartotoja);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vartotoja);
        }

        // GET: Vartotojas/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var vartotoja = await _context.Vartotojas.FindAsync(id);
            if (vartotoja == null)
            {
                return Redirect("~/Home/Nerasta");
            }
            return View(vartotoja);
        }

        // POST: Vartotojas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Vardas,Slaptazodis,Telefonas,EPastas,Miestas,Id")] Vartotoja vartotoja)
        {
            if (id != vartotoja.Id)
            {
                return Redirect("~/Home/Nerasta");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vartotoja);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VartotojaExists(vartotoja.Id))
                    {
                        return Redirect("~/Home/Nerasta");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vartotoja);
        }

        // GET: Vartotojas/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var vartotoja = await _context.Vartotojas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vartotoja == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            return View(vartotoja);
        }

        // POST: Vartotojas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vartotoja = await _context.Vartotojas.FindAsync(id);
            _context.Vartotojas.Remove(vartotoja);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VartotojaExists(int id)
        {
            return _context.Vartotojas.Any(e => e.Id == id);
        }
    }
}

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <style>
        body {
            background-color: #ececec;
        }

        .navbar {
            background-color: #cccccc;
        }

        .footer {
            background-color: #cccccc;
        }
    </style>
</head>
<body>
    @{
        mvc.Models.darbasContext db = new darbasContext();
        var user = db.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/logo.png" alt="" width="50" height="50"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skelbimas" asp-action="Index">Skelbimai</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vartotojas" asp-action="Details" asp-route-id="@user.Id">Profilis</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vartotojas" asp-action="Isiminti">Įsiminti skelbimai</a>
                            </li>
                            <li class="nav-item nav-link text-dark"><i>Prisijungęs kaip <b>@user.Vardas</b></i></li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Atsijungimas">Atsijungti</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Prisijungimas">Prisijungti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Registracija">Registruotis</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- <div class="container">
        <main role="main" class="pb-3">
            @*@RenderBody()*@
        </main>
    </div>-->
    @{
        var allDisabled = "";
        if (@ViewData["kategorija"] as string == null)
        {
            allDisabled = "disabled";
        }
    }
    <div class="container">
        <div class="row py-3">
            <div class="col-3 order-2" id="sticky-sidebar">
                <div class="sticky-top">
                    <h1>Kategorijos</h1>
                    <hr />
                    <!--
    <h5>Paieška pagal kategoriją</h5>
    <div class="form-group row">
        <form asp-action="Index" method="get">
            <div class="col-xs-2">
                <input placeholder="Įveskite dalį kategorijos" type="text" name="kategorija" class="form-control" value="@ViewData["CurrentFilter"]" />
            </div>
            <p class="control">
                <div class="btn-group">
                    <button class="btn btn-primary" asp-controller="Skelbimas" asp-action="Index" type="submit">
                        Paieška
                    </button>
                    <a class="btn btn-primary @allDisabled" asp-action="Index">Atgal į sąrašą</a>
                </div>
            </p>
        </form>
    </div>
    <hr />-->
                    <h5>Kategorijų sąrašas</h5>
                    @foreach (var kategorij in db.Kategorijas)
                    {
                        <h6>
                            <a class="link-info" href="/Skelbimas/Index?kategorija=@kategorij.Pavadinimas">@kategorij.Pavadinimas</a>
                        </h6>
                    }
                </div>
            </div>
            <div class="col" id="main">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Darbo paieška - KTU - IFIN-0/1 - Renatas Jočys
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>