mvc/Models/Skelbima.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace mvc.Models
{
    public partial class Skelbima
    {
        public Skelbima()
        {
            Isiminta = new HashSet<Isimintum>();
            Komentaras = new HashSet<Komentara>();
        }

        [DisplayName("Pavadinimas")]
        public string Pavadinimas { get; set; }
        [DisplayName("Aprašymas")]
        public string Aprasymas { get; set; }
        [DisplayName("Adresas")]
        public string Adresas { get; set; }
        [DisplayName("Užmokestis")]
        public decimal Uzmokestis { get; set; }
        [DisplayName("Sukūrimo data")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime Data { get; set; }
        [DisplayName("Apmokėjimas")]
        public int MokejimoBudas { get; set; }
        [DisplayName("Id")]
        public int Id { get; set; }
        [DisplayName("Sukūrė")]
        public int? FkVartotojasid { get; set; }
        [DisplayName("Kategorija")]
        public int FkKategorijaid { get; set; }

        [DisplayName("Kategorija")]
        public virtual Kategorija FkKategorija { get; set; }
        [DisplayName("Sukūrė")]
        public virtual Vartotoja FkVartotojas { get; set; }
        [DisplayName("Atsiskaitymo būdas")]
        public virtual Apmokejima MokejimoBudasNavigation { get; set; }
        public virtual ICollection<Isimintum> Isiminta { get; set; }
        public virtual ICollection<Komentara> Komentaras { get; set; }
    }
}

mvc/Controllers/IsimintiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc.Models;

namespace mvc.Controllers
{
    public class IsimintiController : Controller
    {
        private readonly darbasContext _context;

        public IsimintiController(darbasContext context)
        {
            _context = context;
        }

        // GET: Isiminti
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var darbasContext = _context.Isiminta.Include(i => i.FkSkelbimas).Include(i => i.FkVartotojas);
            return View(await darbasContext.ToListAsync());
        }

        // GET: Isiminti/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var isimintum = await _context.Isiminta
                .Include(i => i.FkSkelbimas)
                .Include(i => i.FkVartotojas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (isimintum == null)
            {
                return NotFound();
            }

            return View(isimintum);
        }

        // GET: Isiminti/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["FkSkelbimasid"] = new SelectList(_context.Skelbimas, "Id", "Aprasymas");
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "EPastas");
            return View();
        }

        // POST: Isiminti/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,FkSkelbimasid,FkVartotojasid")] Isimintum isimintum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(isimintum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkSkelbimasid"] = new SelectList(_context.Skelbimas, "Id", "Aprasymas", isimintum.FkSkelbimasid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "EPastas", isimintum.FkVartotojasid);
            return View(isimintum);
        }

        // GET: Isiminti/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var isimintum = await _context.Isiminta.FindAsync(id);
            if (isimintum == null)
            {
                return NotFound();
            }
            ViewData["FkSkelbimasid"] = new SelectList(_context.Skelbimas, "Id", "Aprasymas", isimintum.FkSkelbimasid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "EPastas", isimintum.FkVartotojasid);
            return View(isimintum);
        }

        // POST: Isiminti/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FkSkelbimasid,FkVartotojasid")] Isimintum isimintum)
        {
            if (id != isimintum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(isimintum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IsimintumExists(isimintum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkSkelbimasid"] = new SelectList(_context.Skelbimas, "Id", "Aprasymas", isimintum.FkSkelbimasid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "EPastas", isimintum.FkVartotojasid);
            return View(isimintum);
        }

        // GET: Isiminti/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var isimintum = await _context.Isiminta
                .Include(i => i.FkSkelbimas)
                .Include(i => i.FkVartotojas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (isimintum == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            return View(isimintum);
        }

        // POST: Isiminti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var isimintum = await _context.Isiminta.FindAsync(id);
            _context.Isiminta.Remove(isimintum);
            await _context.SaveChangesAsync();
            TempData["pavyko"] = "Skelbimas sėkmingai pamirštas!";
            return Redirect("/Home");
        }

        private bool IsimintumExists(int id)
        {
            return _context.Isiminta.Any(e => e.Id == id);
        }
    }
}

mvc/Controllers/SkelbimasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace mvc.Models
{
    public class SkelbimasController : Controller
    {
        private readonly darbasContext _context;

        public SkelbimasController(darbasContext context)
        {
            _context = context;
        }

        // GET: Skelbimas
        public async Task<IActionResult> Index(string sortOrder, string Raktazodis, int? puslapis, string currentFilter, string kategorija)
        {
            var darbasContext = _context.Skelbimas.Include(s => s.FkKategorija).Include(s => s.FkVartotojas).Include(s => s.MokejimoBudasNavigation);
            if (Raktazodis != null)
            {
                puslapis = 1;
            }
            else
            {
                Raktazodis = currentFilter;
            }
            ViewData["CurrentFilter"] = Raktazodis;
            ViewData["Kategorija"] = kategorija;
            var skelbimai = from s in _context.Skelbimas select s;

            if (!String.IsNullOrEmpty(Raktazodis))
            {
                skelbimai = skelbimai.Where(s => s.Pavadinimas.Contains(Raktazodis));
            }
            if (!String.IsNullOrEmpty(kategorija))
            {
                skelbimai = skelbimai.Where(s => s.FkKategorija.Pavadinimas.Contains(kategorija));
            }

            int pageSize = 5;
            return View(await PaginatedList<Skelbima>.CreateAsync(skelbimai.AsNoTracking().Include(d => d.FkVartotojas), puslapis ?? 1, pageSize));
        }

        // GET: Skelbimas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["ID"] = id;
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var skelbima = await _context.Skelbimas
                .Include(s => s.FkKategorija)
                .Include(s => s.FkVartotojas)
                .Include(s => s.MokejimoBudasNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (skelbima == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var komentarai = _context.Komentaras.Where(a => a.FkSkelbimasid == id).ToList();
            foreach (Komentara c in komentarai)
            {
                var user = await _context.Vartotojas.FirstOrDefaultAsync(z => z.Id == c.FkVartotojasid);
                c.FkVartotojas.Vardas = user.Vardas;
                skelbima.Komentaras.Add(c);
            }

            return View(skelbima);
        }

        // GET: Skelbimas/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas");
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas");
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name");
            return View();
        }

        // POST: Skelbimas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Pavadinimas,Aprasymas,Adresas,Uzmokestis,Data,MokejimoBudas,Id,FkVartotojasid,FkKategorijaid")] Skelbima skelbima)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
                skelbima.Data = DateTime.Now;
                skelbima.FkVartotojasid = user.Id;
                _context.Add(skelbima);
                await _context.SaveChangesAsync();
                TempData["pavyko"] = "Skelbimas buvo sėkmingai sukurtas!";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas", skelbima.FkKategorijaid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas", skelbima.FkVartotojasid);
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name", skelbima.MokejimoBudas);
            return View(skelbima);
        }

        // GET: Skelbimas/Prisiminti
        [Authorize]
        public IActionResult Prisiminti(int id)
        {
            ViewData["ID"] = id;
            var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
            var isiminti = _context.Isiminta.Count(x => x.FkSkelbimasid == id);
            var isi = _context.Isiminta.Where(y => y.FkSkelbimasid == id).ToList();
            foreach (var i in isi)
            {
                if (i.FkVartotojasid == user.Id)
                {
                    TempData["Error"] = "Klaida! Jūs šį skelbimą jau esate įsiminę!";
                    return Redirect("~/Home");
                }
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas");
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas");
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name");
            return View();
        }

        // POST: Skelbimas/Prisiminti
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]

        public async Task<IActionResult> Prisiminti([Bind("FkSkelbimasid,FkVartotojasid")] Isimintum isimintum, int id)
        {
            var isiminti = _context.Isiminta.Count(x => x.FkSkelbimasid == id);
            if (ModelState.IsValid)
            {
                var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
                isimintum.FkSkelbimasid = id;
                isimintum.FkVartotojasid = user.Id;
                _context.Add(isimintum);
                await _context.SaveChangesAsync();
                TempData["pavyko"] = "Skelbimas buvo sėkmingai prisimintas!";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkSkelbimasid"] = new SelectList(_context.Skelbimas, "Id", "Aprasymas", isimintum.FkSkelbimasid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "EPastas", isimintum.FkVartotojasid);
            return View(isimintum);
        }

        // GET: Skelbimas/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

            var skelbima = await _context.Skelbimas
                .Include(s => s.FkKategorija)
                .Include(s => s.FkVartotojas)
                .Include(s => s.MokejimoBudasNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (skelbima == null)
            {
                return Redirect("~/Home/Nerasta");
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas", skelbima.FkKategorijaid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas", skelbima.FkVartotojasid);
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name", skelbima.MokejimoBudas);
            return View(skelbima);
        }

        // POST: Skelbimas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Pavadinimas,Aprasymas,Adresas,Uzmokestis,Data,MokejimoBudas,Id,FkVartotojasid,FkKategorijaid")] Skelbima skelbima)
        {
            if (id != skelbima.Id)
            {
                return Redirect("~/Home/Nerasta");
            }

            if (ModelState.IsValid)
            {
                var user = _context.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
                skelbima.FkVartotojasid = user.Id;
                skelbima.Data = DateTime.Now;
                try
                {
                    _context.Update(skelbima);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkelbimaExists(skelbima.Id))
                    {
                        return Redirect("~/Home/Nerasta");
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["pavyko"] = "Skelbimas buvo sėkmingai atnaujintas!";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkKategorijaid"] = new SelectList(_context.Kategorijas, "Id", "Pavadinimas", skelbima.FkKategorijaid);
            ViewData["FkVartotojasid"] = new SelectList(_context.Vartotojas, "Id", "Vardas", skelbima.FkVartotojasid);
            ViewData["MokejimoBudas"] = new SelectList(_context.Apmokejimas, "Id", "Name", skelbima.MokejimoBudas);
            return View(skelbima);
        }

        // GET: Skelbimas/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return Redirect("~/Home/Nerasta");
            }

mvc/Views/Skelbimas/Create.cshtml
@model mvc.Models.Skelbima

@{
    ViewData["Title"] = "Kurti skelbimą";
}

<h1>Kurti skelbimą</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pavadinimas" class="control-label"></label>
                <input asp-for="Pavadinimas" class="form-control" />
                <span asp-validation-for="Pavadinimas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aprasymas" class="control-label"></label>
                <input asp-for="Aprasymas" class="form-control" />
                <span asp-validation-for="Aprasymas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresas" class="control-label"></label>
                <input asp-for="Adresas" class="form-control" />
                <span asp-validation-for="Adresas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uzmokestis" class="control-label"></label>
                <input asp-for="Uzmokestis" class="form-control" />
                <span asp-validation-for="Uzmokestis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MokejimoBudas" class="control-label"></label>
                <select asp-for="MokejimoBudas" class="form-control" asp-items="ViewBag.MokejimoBudas"></select>
            </div>
            <div class="form-group">
                <label asp-for="FkKategorijaid" class="control-label"></label>
                <select asp-for="FkKategorijaid" class="form-control" asp-items="ViewBag.FkKategorijaid"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Sukurti" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<hr />
<a class="btn btn-primary" asp-controller="Skelbimas" asp-action="Index">Grįžti į skelbimų sąrašą</a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mvc/Views/Skelbimas/Delete.cshtml
@model mvc.Models.Skelbima

@{
    ViewData["Title"] = "Naikinti skelbimą";
}

<h1>Naikinti skelbimą</h1>
@if (User.Identity.Name == (Model.FkVartotojas.EPastas))
{
    <div>
        <h1>@Html.DisplayFor(model => model.Pavadinimas)</h1>
        <hr />
        <dl class="row">
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.Aprasymas)
            </dt>
            <dt class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.Aprasymas)
            </dt>
            <hr />
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.Uzmokestis)
            </dt>
            <dd class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.Uzmokestis)€
            </dd>
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.Adresas)
            </dt>
            <dt class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.Adresas)
            </dt>
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.Data)
            </dt>
            <dd class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.Data)
            </dd>
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.FkKategorija)
            </dt>
            <dd class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.FkKategorija.Pavadinimas)
            </dd>
            <hr />
            <h3 class="text-center">Kontaktai</h3>
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.FkVartotojas.Vardas)
            </dt>
            <dd class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.FkVartotojas.Vardas)
            </dd>
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.FkVartotojas.Telefonas)
            </dt>
            <dd class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.FkVartotojas.Telefonas)
            </dd>
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.FkVartotojas.EPastas)
            </dt>
            <dd class="col-sm-12 text-center">
                <a href="mailto:@Html.DisplayFor(model => model.FkVartotojas.EPastas)">@Html.DisplayFor(model => model.FkVartotojas.EPastas)</a>
            </dd>
            <dt class="col-sm-12 text-center">
                @Html.DisplayNameFor(model => model.MokejimoBudasNavigation)
            </dt>
            <dd class="col-sm-12 text-center">
                @Html.DisplayFor(model => model.MokejimoBudasNavigation.Name)
            </dd>
        </dl>

        <h3>Ar jūs įsitikinęs, kad norite panaikinti šį skelbimą?</h3>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Naikinti skelbimą" class="btn btn-danger" />
            <a class="btn btn-primary" asp-controller="Skelbimas" asp-action="Index">Grįžti į skelbimų sąrašą</a>
        </form>
    </div>

}
else
{
    <h2 class="text-center alert-danger">Klaida! Jūs neturite teisės atlikti šios procedūros!</h2>
    <hr />
    <a class="btn btn-primary" asp-controller="Skelbimas" asp-action="Index">Grįžti į skelbimų sąrašą</a>
}

mvc/Views/Skelbimas/Details.cshtml
@model mvc.Models.Skelbima

@{
    ViewData["Title"] = "Details";
    var error = TempData["Error"] as string;
    var pavyko = TempData["pavyko"] as string;
}
@{
    mvc.Models.darbasContext db = new darbasContext();
}

<a class="btn btn-primary" asp-controller="Skelbimas" asp-action="Index">Grįžti į skelbimų sąrašą</a>
@if (User.Identity.IsAuthenticated)
{
    var user = db.Vartotojas.SingleOrDefault(x => x.EPastas.Equals(User.Identity.Name));
    var isimintasSkelb = db.Isiminta.Where(a => a.FkVartotojasid == user.Id).ToList();
    int count = 0;
    foreach (var item in isimintasSkelb)
    {
        if (item.FkSkelbimasid == Model.Id)
        {
            <a class="btn btn-danger" asp-controller="Isiminti" asp-action="Delete" asp-route-id="@item.Id">Pamiršti skelbimą</a>
            count++;
        }
    }
    if (count == 0)
    {
        <a class="btn btn-primary" asp-action="Prisiminti" asp-route-id="@Model.Id">Įsiminti šį skelbimą</a>
    }
}


<div>
    <h1>@Html.DisplayFor(model => model.Pavadinimas)</h1>
    @if (!string.IsNullOrEmpty(error))
    {
        <h3 class="alert-danger" style="padding:20px">@error</h3>
    }
    @if (!string.IsNullOrEmpty(pavyko))
    {
        <h3 class="alert-success" style="padding:20px">@pavyko</h3>
    }
    <hr />
    <dl class="row">
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.Aprasymas)
        </dt>
        <dt class="col-sm-12 text-center">
            @Html.DisplayFor(model => model.Aprasymas)
        </dt>
        <hr />
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.Uzmokestis)
        </dt>
        <dd class="col-sm-12 text-center">
            @Html.DisplayFor(model => model.Uzmokestis)€
        </dd>
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.Adresas)
        </dt>
        <dt class="col-sm-12 text-center">
            @Html.DisplayFor(model => model.Adresas)
        </dt>
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-12 text-center">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.FkKategorija)
        </dt>
        <dd class="col-sm-12 text-center">
            @Html.DisplayFor(model => model.FkKategorija.Pavadinimas)
        </dd>
        <hr />
        <h3 class="text-center">Kontaktai</h3>
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.FkVartotojas.Vardas)
        </dt>
        <dd class="col-sm-12 text-center">
            <a class="text-dark" asp-area="" asp-controller="Vartotojas" asp-action="Details" asp-route-id="@Model.FkVartotojas.Id">@Html.DisplayFor(model => model.FkVartotojas.Vardas)</a>
        </dd>
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.FkVartotojas.Telefonas)
        </dt>
        <dd class="col-sm-12 text-center">
            @Html.DisplayFor(model => model.FkVartotojas.Telefonas)
        </dd>
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.FkVartotojas.EPastas)
        </dt>
        <dd class="col-sm-12 text-center">
            <a href="mailto:@Html.DisplayFor(model => model.FkVartotojas.EPastas)">@Html.DisplayFor(model => model.FkVartotojas.EPastas)</a>
        </dd>
        <dt class="col-sm-12 text-center">
            @Html.DisplayNameFor(model => model.MokejimoBudasNavigation)
        </dt>
        <dd class="col-sm-12 text-center">
            @Html.DisplayFor(model => model.MokejimoBudasNavigation.Name)
        </dd>
    </dl>
</div>
<hr />
<div class="text-center">
    <h1 class="text-center">Komentarai</h1>
    <a class="btn btn-primary" asp-action="Komentuoti" asp-route-id="@Model.Id">Rašyti komentarą</a>
    @{
        int kiek = 0;
        foreach (var item in Model.Komentaras.ToList())
        {
            <div class="alert-primary">
                <h5><a class="text-dark" asp-area="" asp-controller="Vartotojas" asp-action="Details" asp-route-id="@item.FkVartotojas.Id">@item.FkVartotojas.Vardas</a> pakomentavo:</h5>
                <p> @item.Komentaras</p>
            </div>
            kiek++;
        }
        if (kiek == 0)
        {
            <h5 class="text-center">Komentarų nėra!</h5>
        }
    }

</div>
<div>
    <hr />
    <a class="btn btn-primary" asp-controller="Skelbimas" asp-action="Index">Grįžti į skelbimų sąrašą</a>
    @if (User.Identity.Name == (Model.FkVartotojas.EPastas))
    {
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Redaguoti skelbimą</a>
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Naikinti skelbimą</a>
    }
</div>